name: Run 2D Scraper

on:
  schedule:
    # 1. မနက် ၁၁:၀၀ ထွက်ဂဏန်းအတွက် -> မြန်မာစံတော်ချိန် ၁၁:၀၄ AM တွင် Run မည်
    - cron: '34 4 * * *'
    
    # 2. မနက် ၁၂:၀၁ ထွက်ဂဏန်းအတွက် -> မြန်မာစံတော်ချိန် ၁၂:၀၅ PM တွင် Run မည်
    - cron: '35 5 * * *'
    
    # 3. ညနေ ၃:၀၀ ထွက်ဂဏန်းအတွက် -> မြန်မာစံတော်ချိန် ၃:၀၄ PM တွင် Run မည်
    - cron: '34 8 * * *'
    
    # 4. ညနေ ၄:၃၀ ထွက်ဂဏန်းအတွက် -> မြန်မာစံတော်ချိန် ၄:၃၄ PM တွင် Run မည်
    - cron: '04 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests supabase

      - name: Run Scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python scrape_2d.py
